name: Processar Planilha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  processar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # ou a versão que você estiver usando

    - name: Instalar dependências
      run: |
        pip install gspread oauth2client requests

    - name: Executar script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        KOMMO_API_TOKEN: ${{ secrets.KOMMO_API_TOKEN }}
      run: |
        python send.py
