name: Run CONTROLEMELHORENVIO

on:
  push:
    branches:
      - main  # Substitua pela sua branch principal
  schedule:
    - cron: '0 0 * * *'  # Configuração para rodar diariamente à meia-noite

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ajuste para a versão de Python necessária

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests fuzzywuzzy

      - name: Run CONTROLEMELHORENVIO script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MELHOR_ENVIO_CLIENT_ID: ${{ secrets.MELHOR_ENVIO_CLIENT_ID }}
          MELHOR_ENVIO_CLIENT_SECRET: ${{ secrets.MELHOR_ENVIO_CLIENT_SECRET }}
        run: |
          python CONTROLEMELHORENVIO.py  # Ajuste o caminho se necessário
