name: Atualizar Planilha

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Ajuste o horário conforme necessário para agendamento

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Especifique a versão do Python, ex: '3.8'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar script Python
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        MELHOR_ENVIO_ACCESS_TOKEN: ${{ secrets.MELHOR_ENVIO_ACCESS_TOKEN }}
        MELHOR_ENVIO_CLIENT_ID: ${{ secrets.MELHOR_ENVIO_CLIENT_ID }}
        MELHOR_ENVIO_CLIENT_SECRET: ${{ secrets.MELHOR_ENVIO_CLIENT_SECRET }}
        KOMMO_ACCESS_TOKEN: ${{ secrets.KOMMO_ACCESS_TOKEN }}
      run: |
        python CONTROLEMELHORENVIO.py
