name: Atualizar Planilha

on:
  schedule:
    - cron: '0 * * * *'  # Este cron agendará para rodar a cada hora
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub

jobs:
  update-planilha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3  # Atualize para a versão mais recente

    - name: Configurar Python
      uses: actions/setup-python@v4  # Atualize para a versão mais recente
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar script
      run: |
        python planilha.py
