name: Atualizar Planilha

on:
  schedule:
    - cron: '0 * * * *'  # Agenda para rodar a cada hora
  workflow_dispatch:  # Permite execução manual pelo GitHub

jobs:
  update-planilha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3  # Clona o repositório para o ambiente de execução

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Especifica a versão do Python

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt  # Instala dependências do Python listadas em requirements.txt

    - name: Executar script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Injeta as credenciais do Google
      run: |
        python planilha.py  # Executa o script Python
